export const collaborativeOptions = [
  { label: "English", value: "english" },
  { label: "French", value: "french" },
  { label: "German", value: "german" },
  { label: "Italian", value: "italian" },
  { label: "Japanese", value: "japanese" },
  { label: "Chinese", value: "chinese" },
  { label: "Korean", value: "korean" },
  { label: "Spanish", value: "spanish" },
  { label: "Portuguese", value: "portuguese" },
  { label: "Arabic", value: "arabic" },
  { label: "Farsi", value: "farsi" },
  { label: "Thai", value: "thai" },
];

export const musicStylesOptions = [
  { label: "Ambient", value: "ambient" },
  { label: "Blues", value: "blues" },
  { label: "Cinematic", value: "cinematic" },
  { label: "Classical", value: "classical" },
  { label: "Country", value: "country" },
  { label: "Disco", value: "disco" },
  { label: "Dubstep", value: "dubstep" },
  { label: "Epic", value: "epic" },
  { label: "Folk", value: "folk" },
  { label: "Funk", value: "funk" },
  { label: "Hip hop", value: "hip-hop" },
  { label: "Holiday", value: "holiday" },
  { label: "House", value: "house" },
  { label: "Indie Pop", value: "indie-pop" },
  { label: "Jazz", value: "jazz" },
  { label: "Latin", value: "latin" },
  { label: "Metal", value: "metal" },
  { label: "Neo-Soul", value: "neo-soul" },
  { label: "New Age", value: "new-age" },
  { label: "Orchestral", value: "orchestral" },
  { label: "Piano", value: "piano" },
  { label: "Pop", value: "pop" },
  { label: "R&B", value: "rnb" },
  { label: "Rap", value: "rap" },
  { label: "Reggae", value: "reggae" },
  { label: "Rock", value: "rock" },
  { label: "Samba", value: "samba" },
  { label: "Trap", value: "trap" },
  { label: "Underscore", value: "underscore" },
  { label: "Video Game", value: "video-game" },
  { label: "World", value: "world" },
];

export const instrumentsOptions = [
  { label: "Accordion", value: "accordion" },
  { label: "Acoustic Bass", value: "acoustic-bass" },
  { label: "Acoustic Guitar", value: "acoustic-guitar" },
  { label: "Banjo", value: "banjo" },
  { label: "Bassoon", value: "bassoon" },
  { label: "Bells", value: "bells" },
  { label: "Bongos", value: "bongos" },
  { label: "Brass", value: "brass" },
  { label: "Cello", value: "cello" },
  { label: "Choir", value: "choir" },
  { label: "Clapping", value: "clapping" },
  { label: "Clarinet", value: "clarinet" },
  { label: "Drum Kit", value: "drum-kit" },
  { label: "Duduk", value: "duduk" },
  { label: "Electric Bass", value: "electric-bass" },
  { label: "Electric Guitar", value: "electric-guitar" },
  { label: "Electronic Drums", value: "electronic-drums" },
  { label: "Erhu", value: "erhu" },
  { label: "Female Vocals", value: "female-vocals" },
  { label: "Flute", value: "flute" },
  { label: "French horn", value: "french-horn" },
  { label: "Gong", value: "gong" },
  { label: "Harmonica", value: "harmonica" },
  { label: "Harp", value: "harp" },
  { label: "Keyboard", value: "keyboard" },
  { label: "Male Vocals", value: "male-vocals" },
  { label: "Marimba", value: "marimba" },
  { label: "Music Box", value: "music-box" },
  { label: "Oboe", value: "oboe" },
  { label: "Orchestra", value: "orchestra" },
  { label: "Orchestral Percussion", value: "orchestral-percussion" },
  { label: "Organ", value: "organ" },
  { label: "Percussion", value: "percussion" },
  { label: "Piano", value: "piano" },
  { label: "Saxophone", value: "saxophone" },
  { label: "SFX", value: "sfx" },
  { label: "Snapping", value: "snapping" },
  { label: "Strings", value: "strings" },
  { label: "Synths", value: "synths" },
  { label: "Trombone", value: "trombone" },
  { label: "Trumpet", value: "trumpet" },
  { label: "Tuba", value: "tuba" },
  { label: "Ukulele", value: "ukulele" },
  { label: "Violin", value: "violin" },
  { label: "Vocals", value: "vocals" },
  { label: "Woodwinds", value: "woodwinds" },
  { label: "World Percussion", value: "world-percussion" },
  { label: "Xylophone", value: "xylophone" },
];
