export const SELECTED = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
];

export const CATEGORIES = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 5,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 6,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 7,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 8,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 9,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 10,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 11,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
  {
    id: 12,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
  },
];

export const JOBS_PROPS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Linkin Park",
    songName: "Numb",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Mike Shinoda",
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Coldplay",
    songName: "Fix You",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Chris Martin",
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Taylor Swift",
    songName: "Blank Space",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Taylor Swift",
  },
  {
    id: 5,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Adele",
    songName: "Hello",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Adele",
  },
  {
    id: 6,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Imagine Dragons",
    songName: "Believer",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Dan Reynolds",
  },
  {
    id: 7,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Maroon 5",
    songName: "Sugar",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Adam Levine",
  },
  {
    id: 8,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Ed Sheeran",
    songName: "Shape of You",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Ed Sheeran",
  },
  {
    id: 9,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Billie Eilish",
    songName: "Bad Guy",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Billie Eilish",
  },
  {
    id: 10,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Bruno Mars",
    songName: "Uptown Funk",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Mark Ronson",
  },
  {
    id: 11,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Dua Lipa",
    songName: "Don't Start Now",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Dua Lipa",
  },
  {
    id: 12,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Katy Perry",
    songName: "Firework",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Katy Perry",
  },
  {
    id: 13,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "The Weeknd",
    songName: "Blinding Lights",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "The Weeknd",
  },
  {
    id: 14,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Post Malone",
    songName: "Circles",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Post Malone",
  },
  {
    id: 15,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Selena Gomez",
    songName: "Lose You to Love Me",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Selena Gomez",
  },
  {
    id: 16,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Shawn Mendes",
    songName: "Stitches",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Shawn Mendes",
  },
  {
    id: 17,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Rihanna",
    songName: "Diamonds",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Sia",
  },
  {
    id: 18,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Halsey",
    songName: "Without Me",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Halsey",
  },
  {
    id: 19,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Nick Jonas",
    songName: "Jealous",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Nick Jonas",
  },
  {
    id: 20,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Ariana Grande",
    songName: "Thank U, Next",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Ariana Grande",
  },
  {
    id: 21,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Travis Scott",
    songName: "Sicko Mode",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Travis Scott",
  },
  {
    id: 22,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Lil Nas X",
    songName: "Old Town Road",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Lil Nas X",
  },
  {
    id: 23,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Miley Cyrus",
    songName: "Wrecking Ball",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Miley Cyrus",
  },
  {
    id: 24,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Beyoncé",
    songName: "Halo",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Beyoncé",
  },
  {
    id: 25,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Jennifer Lopez",
    songName: "On The Floor",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "RedOne",
  },
  {
    id: 26,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Snoop Dogg",
    songName: "Drop It Like It's Hot",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Pharrell Williams",
  },
  {
    id: 27,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Usher",
    songName: "Yeah!",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Usher",
  },
  {
    id: 28,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Kendrick Lamar",
    songName: "HUMBLE.",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Kendrick Lamar",
  },
  {
    id: 29,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Demi Lovato",
    songName: "Sorry Not Sorry",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Demi Lovato",
  },
  {
    id: 30,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Niall Horan",
    songName: "Slow Hands",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Niall Horan",
  },
];

export const SAVED_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    savedJobs: true,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    savedJobs: true,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    savedJobs: true,
  },
];

export const APPLIED_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
  {
    id: 4,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    appliedJobs: true,
  },
];

export const ACTIVE_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: true,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: true,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: true,
  },
];

export const INACTIVE_JOBS = [
  {
    id: 1,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: false,
  },
  {
    id: 2,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: false,
  },
  {
    id: 3,
    imgSong: "https://docs.material-tailwind.com/img/face-2.jpg",
    singerName: "Paramore",
    songName: "Brick by Boring Brick",
    imgComposer: "https://docs.material-tailwind.com/img/face-4.jpg",
    composerName: "Hayley Williams",
    activeJobs: false,
  },
];
