export const messages = [
  {
    chatId: 1,
    detail: [
      {
        userId: 1,
        message: "Hello, how are you?",
        datetime: "09:15",
        currentUser: true,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 2,
        message: "I'm doing well, thanks! How about you?",
        datetime: "09:16",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 1,
        message: "I'm good, just busy with work.",
        datetime: "09:17",
        currentUser: true,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 2,
        message: "I can relate! What are you working on?",
        datetime: "09:18",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 2,
        message: "Hey, are we still on for tomorrow?",
        datetime: "09:18",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
    ],
  },
  {
    chatId: 2,
    detail: [
      {
        userId: 1,
        message: "",
        datetime: "09:37",
        currentUser: true,
        isCard: true,
        cardType: 1,
      },
      {
        userId: 1,
        message: "Check out this new project idea!",
        datetime: "09:37",
        currentUser: true,
        isCard: false,
        cardType: 0,
      },
    ],
  },
  {
    chatId: 3,
    detail: [
      {
        userId: 3,
        message: "Hello, how are you?",
        datetime: "09:15",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 3,
        message: "I hope you had a good weekend!",
        datetime: "09:16",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 3,
        message: "I have a problem",
        datetime: "09:17",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 3,
        message:
          "I've been working on the project. but is not what the client want, I need your help",
        datetime: "09:18",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
      {
        userId: 3,
        message: "Can you help me?",
        datetime: "09:19",
        currentUser: false,
        isCard: false,
        cardType: 0,
      },
    ],
  },
];
